version: '3'

env:
  GO_VERSION: 1.23.4

tasks:
  install-go:
    cmds:
      - wget "https://golang.org/dl/go{{.GO_VERSION}}.linux-amd64.tar.gz"
      - sudo tar -C /usr/local -xzf go{{.GO_VERSION}}.linux-amd64.tar.gz
      - rm go$(GO_VERSION).linux-amd64.tar.gz

  init-go:
    cmds:
      - echo 'export PATH=$$PATH:/usr/local/go/bin' >> {{.HOME}}/.bashrc
      - echo 'export PATH=$$PATH:{{.HOME}}/go/bin' >> {{.HOME}/.bashrc